require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  ExtraDetails: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'generated/**/*.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Layout/EmptyLines: { Enabled: false }
Layout/HashAlignment: { EnforcedHashRocketStyle: table, EnforcedColonStyle: table }
Layout/LineLength: { Enabled: false }
Layout/TrailingEmptyLines: { Enabled: true }
Metrics: { Enabled: false }
RSpec/FilePath: { Enabled: false }
Style/ClassAndModuleChildren: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DocumentationMethod: { Enabled: false }
Style/HashEachMethods: { Enabled: true }
Style/HashTransformKeys: { Enabled: true }
Style/HashTransformValues: { Enabled: true }
Style/IfUnlessModifier: { Enabled: false }
Style/StringLiterals: { Enabled: false }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: comma }
Style/GlobalVars: { AllowedVariables: $stats }